### ISSUE TITLE
error when run `yarn dev` 

### ISSUE THREAD

**Issue by zhfnjust** [TAAL-GmbH/taal-wallet#6]
![image](https://github.com/TAAL-GmbH/taal-wallet/assets/995909/438b1b5b-c1ee-4358-a6f6-d571fec3feb1)

**Comment by untitledlt** [comment]
`yarn add firebase-admin` should fix this issue for now. 

Firebase is not used in taal-wallet but it's required for push notifications server which is not implemented.

**Comment by untitledlt** [comment]
solved
